### ISSUE TITLE
Updated Model for 2020 Season

### ISSUE THREAD

**Issue by Mijobar** [JJTimmons/ff#31]
Has the model been updated for the 2020 draft season? If not, how can I update it. Thanks!

**Comment by JJTimmons** [comment]
So the model has been updated, but I need to do more tinkering so it updates periodically (every 6 hours or so). Check it out and let me know if it matches expectations

**Comment by Mijobar** [comment]
Hello!

Thank you and it appears to be matching expectations. Helped me come in second last year and hoping for a first place victory this year! Thanks again!

**Comment by JJTimmons** [comment]
No problem and good luck! That's good to hear that you came in second place, here's hoping you win it all this year
