### ISSUE TITLE
2022 Update?

### ISSUE THREAD

**Issue by mattchernando** [jjtimmons/ff#49]
will this have a 2022 update?

**Comment by jjtimmons** [comment]
ok yeah I'll update it. I'm always a bit slow. _this_ is the year I stick it in a container and set up monitoring and stuff so it just runs without me manually triggering it (🤞 )

**Comment by mattchernando** [comment]
You are awesome! Thank you so much

**Comment by jjtimmons** [comment]
Just updated the scraping + redeployed: https://www.ffdraft.app/

Please let me know if you run into any issues

**Comment by jjtimmons** [comment]
I just set up daily scrapes so it should be kept up to date or I'll get notified if there's an error
